# Generated by Django 2.1.2 on 2018-10-17 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomarticulo', models.CharField(db_column='DenomArticulo', max_length=200, verbose_name='Denominación del Artículo')),
                ('descarticulo', models.TextField(blank=True, db_column='DescArticulo', null=True, verbose_name='Descripción del Artículo')),
                ('precio', models.FloatField(blank=True, db_column='Precio', null=True, verbose_name='Precio')),
                ('existencia', models.FloatField(blank=True, db_column='Existencia', null=True, verbose_name='Existencia')),
                ('tipoarticulo', models.CharField(blank=True, db_column='TipoArticulo', max_length=20, null=True, verbose_name='Tipo de Artículo')),
            ],
            options={
                'verbose_name_plural': 'Artículos',
                'verbose_name': 'Artículo',
                'db_table': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomcliente', models.CharField(db_column='DenomCliente', max_length=200, verbose_name='Denominación del Cliente')),
                ('desccliente', models.TextField(blank=True, db_column='DescCliente', null=True, verbose_name='Descripción del Cliente')),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='FechaRegistro', null=True, verbose_name='Fecha de Registro')),
                ('clienteactivo', models.CharField(db_column='ClienteActivo', max_length=1, verbose_name='Cliente Activo')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'verbose_name': 'Cliente',
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='DetVentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(db_column='Cantidad', verbose_name='Cantidad')),
                ('idarticulo', models.IntegerField(db_column='IdArticulo', verbose_name='Articulo')),
                ('precio', models.FloatField(blank=True, db_column='Precio', null=True, verbose_name='Precio')),
                ('monto', models.FloatField(blank=True, db_column='Monto', null=True, verbose_name='Monto')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Ventas',
                'verbose_name': 'Detalle de Venta',
                'db_table': 'DetVentas',
            },
        ),
        migrations.CreateModel(
            name='VentasDiarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerofactura', models.CharField(db_column='NumeroFactura', max_length=20, verbose_name='Número de Factura')),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True, verbose_name='Fecha')),
                ('hora', models.DateTimeField(blank=True, db_column='Hora', null=True, verbose_name='Hora')),
                ('anulada', models.CharField(db_column='Anulada', max_length=1, verbose_name='Anulada')),
                ('totalarticulos', models.FloatField(db_column='TotalArticulos', verbose_name='Total Artículos')),
                ('totalfactura', models.FloatField(blank=True, db_column='TotalFactura', null=True, verbose_name='Total Factura')),
                ('guardada', models.CharField(db_column='Guardada', max_length=1, verbose_name='Guardada')),
                ('idcliente', models.ForeignKey(db_column='IdCliente', help_text='Seleccione Cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='idcliente_ventasdiarias', to='ventas.Clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name_plural': 'Ventas Diarias',
                'verbose_name': 'Venta Diaria',
                'db_table': 'VentasDiarias',
            },
        ),
        migrations.AddField(
            model_name='detventas',
            name='idventa',
            field=models.ForeignKey(db_column='IdVenta', help_text='Seleccione Venta', on_delete=django.db.models.deletion.DO_NOTHING, related_name='idventa_detventas', to='ventas.VentasDiarias', verbose_name='Venta'),
        ),
    ]
