# Generated by Django 2.1.2 on 2018-10-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'ordering': ['id'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='detventas',
            options={'ordering': ['idventa'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Ventas'},
        ),
        migrations.AlterModelOptions(
            name='ventasdiarias',
            options={'ordering': ['numerofactura', 'fecha'], 'verbose_name': 'Venta Diaria', 'verbose_name_plural': 'Ventas Diarias'},
        ),
        migrations.AlterField(
            model_name='detventas',
            name='idarticulo',
            field=models.ForeignKey(db_column='IdArticulo', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.Articulos', verbose_name='Articulo'),
        ),
    ]
